# Site settings
title: Chris Norval
header-img: img/home-bg.jpg
email: blog@cnorval.com
description: "A blog on R, statistics, machine learning and data science."
baseurl: ""
url: "http://cnorval.github.io"
twitter_username: cnorval
github_username:  cnorval
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
